name: Unit testing for the server.
on:
  push:
    paths:
      - packages/server/**
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    # docker container
    container: node:lts-alpine3.14
    env:
      rootDir: ./packages/server
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js, and Yarn
        working-directory: ${{env.rootDir}}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        working-directory: ${{env.rootDir}}
        run: yarn
      - name: Run Tests
        working-directory: ${{env.rootDir}}
        run: yarn test
        env:
          NODE_ENV: test
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
