name: Unit testing for the server.
on:
  push:
    paths:
      - packages/server/**
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      rootDir: ./packages/server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js, and Yarn
        working-directory: ${{env.rootDir}}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        working-directory: ${{env.rootDir}}
        run: yarn
      - name: Run Tests
        working-directory: ${{env.rootDir}}
        run: yarn test
